spring.application.name=budgeting

spring.jpa.hibernate.ddl-auto=update


spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash
spring.ai.google.genai.chat.options.temperature=0.0
spring.ai.google.genai.chat.options.response-mime-type=text/plain

app.ai.tts.voice=Kore
app.ai.tts.model=gemini-3.1-flash-tts-preview

spring.ai.model.audio.speech=gemini-3.5-flash

logging.level.org.springframework.ai=DEBUG